import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@styles/layout.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </>
  )
}

export default Home
