import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@styles/layout.module.css'
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'
import Container from '@mui/material/Container'

const Home: NextPage = () => {
  return (
    <Container maxWidth='desktop' component={'main'} sx={{ display: 'flex', justifyContent: 'space-around', alignItems: 'center', minHeight: '100vh', flexWrap: 'wrap', width: '100%' }}>

      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box width={'40%'}>
        <Typography variant='h3' sx={{ fontFamily: 'inherit', fontWeight: 'inherit' }} >
          Everything you are looking for is here.
        </Typography>

        <Typography variant='subtitle2' component={'p'} sx={{ fontFamily: 'inherit', fontWeight: 'inherit' }}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam
          volutpat commodo sed egestas egestas fringilla. Faucibus ornare
          suspendisse sed nisi lacus sed viverra tellus in. Faucibus nisl
          tincidunt eget nullam non nisi. Cursus mattis molestie a iaculis at
          erat.
        </Typography>
      </Box>

      <Box width={'25%'}>
        <img src='img_home.jpg' alt='shopping cart' style={{ width: '100%', height: 'auto' }} />
      </Box>

    </Container>
  )
}

export default Home
